name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: 17.0.5-$(date +%s)

    steps:
      - uses: actions/checkout@v3
 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker container and push
        id: docker_build
        uses: docker/build-push-action@v3
        env:
          RELEASE_VERSION: ${{ steps.next.outputs.version }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            pharndt/amazoncorretto:latest
            pharndt/amazoncorretto:${{env.RELEASE_VERSION}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.next.outputs.version }}
        with:
          tag_name: ${{env.RELEASE_VERSION}}
          release_name: ${{env.RELEASE_VERSION}}
          body: |
            Docker tag: `pharndt/amazoncorretto:${{env.RELEASE_VERSION}}`
            Changes in this Release
              - Security updates
          draft: false
          prerelease: false
