name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * 0'
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
 
      - uses: philipparndt/get-release-number@v1
        id: next
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          releaseType: "patch"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker container and push
        id: docker_build
        uses: docker/build-push-action@v3
        env:
          RELEASE_VERSION: ${{ steps.next.outputs.version }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            pharndt/amazoncorretto:latest
            pharndt/amazoncorretto:17.0.5-${{env.RELEASE_VERSION}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.next.outputs.version }}
        with:
          tag_name: ${{env.RELEASE_VERSION}}
          release_name: ${{env.RELEASE_VERSION}}
          body: |
            Docker tag: `pharndt/amazoncorretto:17.0.5-${{env.RELEASE_VERSION}}`
            Changes in this Release
              - Security updates
          draft: false
          prerelease: false
